name: "Danger"

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v4

      - name: Run Danger
        uses: danger/kotlin@1.3.3
        with:
          dangerfile: dangerfile.kts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
