name: "Danger"

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Danger
        run: gem install danger

      - name: Run Danger
        run: danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
